// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package logic

import (
	_ "sviwo/internal/logic/apptext"
	_ "sviwo/internal/logic/biz/ctx"
	_ "sviwo/internal/logic/car"
	_ "sviwo/internal/logic/common"
	_ "sviwo/internal/logic/home"
	_ "sviwo/internal/logic/middleware"
	_ "sviwo/internal/logic/tdengine"
	_ "sviwo/internal/logic/travelrecord"
	_ "sviwo/internal/logic/user"
	_ "sviwo/internal/logic/userauth"
	_ "sviwo/internal/logic/version"
)
