# CLI tool, only in development environment.
# https://goframe.org/pages/viewpage.action?pageId=3673173
# 工具相关配置
gfcli:
  # 工具编译/项目打包配置
  build:
    name: "sviwo-api"
    arch: "amd64"
    system: "linux,darwin,windows"
    mod: ""
    cgo: 0
    packSrc: "manifest/config/config-dev.yaml,manifest/i18n,resource/public,resource/template"
    output: "manifest/docker/sviwo/bin/sviwo-api"

  # dao生成
  gen:
    dao:
      - link: "mysql:root:gyc1993@tcp(114.115.135.233:3306)/sviwo"
        descriptionTag: true
        noModelComment: true
        withTime: true
        removePrefix: "sw_"