// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"sviwo/internal/dao/internal"
)

// internalAppTextDao is internal type for wrapping internal DAO implements.
type internalAppTextDao = *internal.AppTextDao

// appTextDao is the data access object for table sw_app_text.
// You can define custom methods on it to extend its functionality as you wish.
type appTextDao struct {
	internalAppTextDao
}

var (
	// AppText is globally public accessible object for table sw_app_text operations.
	AppText = appTextDao{
		internal.NewAppTextDao(),
	}
)

// Fill with you ideas below.
