// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"sviwo/internal/dao/internal"
)

// internalAppLogDao is internal type for wrapping internal DAO implements.
type internalAppLogDao = *internal.AppLogDao

// appLogDao is the data access object for table sw_app_log.
// You can define custom methods on it to extend its functionality as you wish.
type appLogDao struct {
	internalAppLogDao
}

var (
	// AppLog is globally public accessible object for table sw_app_log operations.
	AppLog = appLogDao{
		internal.NewAppLogDao(),
	}
)

// Fill with you ideas below.
