// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"sviwo/internal/dao/internal"
)

// internalAppMediaDao is internal type for wrapping internal DAO implements.
type internalAppMediaDao = *internal.AppMediaDao

// appMediaDao is the data access object for table sw_app_media.
// You can define custom methods on it to extend its functionality as you wish.
type appMediaDao struct {
	internalAppMediaDao
}

var (
	// AppMedia is globally public accessible object for table sw_app_media operations.
	AppMedia = appMediaDao{
		internal.NewAppMediaDao(),
	}
)

// Fill with you ideas below.
