// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"sviwo/internal/dao/internal"
)

// internalAppParamDao is internal type for wrapping internal DAO implements.
type internalAppParamDao = *internal.AppParamDao

// appParamDao is the data access object for table sw_app_param.
// You can define custom methods on it to extend its functionality as you wish.
type appParamDao struct {
	internalAppParamDao
}

var (
	// AppParam is globally public accessible object for table sw_app_param operations.
	AppParam = appParamDao{
		internal.NewAppParamDao(),
	}
)

// Fill with you ideas below.
