// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"sviwo/internal/dao/internal"
)

// internalAppVideosDao is internal type for wrapping internal DAO implements.
type internalAppVideosDao = *internal.AppVideosDao

// appVideosDao is the data access object for table sw_app_videos.
// You can define custom methods on it to extend its functionality as you wish.
type appVideosDao struct {
	internalAppVideosDao
}

var (
	// AppVideos is globally public accessible object for table sw_app_videos operations.
	AppVideos = appVideosDao{
		internal.NewAppVideosDao(),
	}
)

// Fill with you ideas below.
