// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"sviwo/internal/dao/internal"
)

// internalBatteryDao is internal type for wrapping internal DAO implements.
type internalBatteryDao = *internal.BatteryDao

// batteryDao is the data access object for table sw_battery.
// You can define custom methods on it to extend its functionality as you wish.
type batteryDao struct {
	internalBatteryDao
}

var (
	// Battery is globally public accessible object for table sw_battery operations.
	Battery = batteryDao{
		internal.NewBatteryDao(),
	}
)

// Fill with you ideas below.
