// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"sviwo/internal/dao/internal"
)

// internalCarDao is internal type for wrapping internal DAO implements.
type internalCarDao = *internal.CarDao

// carDao is the data access object for table sw_car.
// You can define custom methods on it to extend its functionality as you wish.
type carDao struct {
	internalCarDao
}

var (
	// Car is globally public accessible object for table sw_car operations.
	Car = carDao{
		internal.NewCarDao(),
	}
)

// Fill with you ideas below.
