// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"sviwo/internal/dao/internal"
)

// internalTravelRecordDao is internal type for wrapping internal DAO implements.
type internalTravelRecordDao = *internal.TravelRecordDao

// travelRecordDao is the data access object for table sw_travel_record.
// You can define custom methods on it to extend its functionality as you wish.
type travelRecordDao struct {
	internalTravelRecordDao
}

var (
	// TravelRecord is globally public accessible object for table sw_travel_record operations.
	TravelRecord = travelRecordDao{
		internal.NewTravelRecordDao(),
	}
)

// Fill with you ideas below.
