// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"sviwo/internal/dao/internal"
)

// internalUserAuthDao is internal type for wrapping internal DAO implements.
type internalUserAuthDao = *internal.UserAuthDao

// userAuthDao is the data access object for table sw_user_auth.
// You can define custom methods on it to extend its functionality as you wish.
type userAuthDao struct {
	internalUserAuthDao
}

var (
	// UserAuth is globally public accessible object for table sw_user_auth operations.
	UserAuth = userAuthDao{
		internal.NewUserAuthDao(),
	}
)

// Fill with you ideas below.
