// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"sviwo/internal/dao/internal"
)

// internalUserCarDao is internal type for wrapping internal DAO implements.
type internalUserCarDao = *internal.UserCarDao

// userCarDao is the data access object for table sw_user_car.
// You can define custom methods on it to extend its functionality as you wish.
type userCarDao struct {
	internalUserCarDao
}

var (
	// UserCar is globally public accessible object for table sw_user_car operations.
	UserCar = userCarDao{
		internal.NewUserCarDao(),
	}
)

// Fill with you ideas below.
