// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"sviwo/internal/dao/internal"
)

// internalUserDeviceDao is internal type for wrapping internal DAO implements.
type internalUserDeviceDao = *internal.UserDeviceDao

// userDeviceDao is the data access object for table sw_user_device.
// You can define custom methods on it to extend its functionality as you wish.
type userDeviceDao struct {
	internalUserDeviceDao
}

var (
	// UserDevice is globally public accessible object for table sw_user_device operations.
	UserDevice = userDeviceDao{
		internal.NewUserDeviceDao(),
	}
)

// Fill with you ideas below.
