// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"sviwo/internal/dao/internal"
)

// internalUserThirdAccountDao is internal type for wrapping internal DAO implements.
type internalUserThirdAccountDao = *internal.UserThirdAccountDao

// userThirdAccountDao is the data access object for table sw_user_third_account.
// You can define custom methods on it to extend its functionality as you wish.
type userThirdAccountDao struct {
	internalUserThirdAccountDao
}

var (
	// UserThirdAccount is globally public accessible object for table sw_user_third_account operations.
	UserThirdAccount = userThirdAccountDao{
		internal.NewUserThirdAccountDao(),
	}
)

// Fill with you ideas below.
