// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"sviwo/internal/dao/internal"
)

// internalVersionDao is internal type for wrapping internal DAO implements.
type internalVersionDao = *internal.VersionDao

// versionDao is the data access object for table sw_version.
// You can define custom methods on it to extend its functionality as you wish.
type versionDao struct {
	internalVersionDao
}

var (
	// Version is globally public accessible object for table sw_version operations.
	Version = versionDao{
		internal.NewVersionDao(),
	}
)

// Fill with you ideas below.
